
<?php

// Your API Key and secret
$apiKey = "98bnv6b82fkrpma53h6zsff5";
$Secret = "CVZDcjFHvK";

// Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
$signature = hash("sha256", $apiKey.$Secret.time());

// Example of call to the API
$endpoint = "https://api.test.hotelbeds.com/hotel-api/1.0/status";

$request = new http\Client\Request("GET",
    $endpoint,
    [ "Api-Key"     => $apiKey,
      "X-Signature" => $signature,
      "Accept"      => "application/xml" ]);
try
{

    $client = new http\Client;

    $client->enqueue($request)->send();



    // pop the last retrieved response

    $response = $client->getResponse();

    if ($response->getResponseCode() != 200) {  

       printf("%s returned '%s' (%d)\n",

           $response->getTransferInfo("effective_url"),

           $response->getInfo(),

           $response->getResponseCode()

       );

    } else {

       printf($response->getBody());

    }

} catch (Exception $ex) {

    printf("Error while sending request, reason: %s\n",$ex->getMessage());

}
?>